development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: <%= ENV["DATABASE_ADAPTER"] || "mysql2" %>
  encoding: utf8
  database: <%= ENV["DATABASE_NAME"] %>
  pool: <%= ENV["DATABASE_POOL"] || 5 %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] || "127.0.0.1" %>
  port: <%= ENV["DATABASE_PORT"] || 3306 %>
