# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f8140ea5ff6d14f1be2aa083c09f7543c91475d9cbd0851335aecc698dc8930aa4fe2e8cd204a6fdbea3e4f7d95b23e33ce232a975a932932497b74fc32371c

test:
  secret_key_base: 79bc9854ebf43210911005788e98c76883aad1fe3342c48a5fa99b0aa76760287883a6d51d523d1e0f6a499fa28eef56c0f24c4fa82034b20fbc941a8a3a6d6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
