#
# Licenses
#
License.create(
  title: "Creative Commons Attribution 4.0 International",
  url: "https://creativecommons.org/licenses/by/4.0/",
  terms: <<-EOS
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
EOS
)
License.create(
  title: "Creative Commons Attribution-NonCommercial 4.0 International",
  url: "https://creativecommons.org/licenses/by-nc/4.0/",
  terms: <<-EOS
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.
EOS
)
License.create(
  title: "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International",
  url: "https://creativecommons.org/licenses/by-nc-nd/4.0/",
  terms: <<-EOS
<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.
EOS
)
License.create(
  title: "Creative Commons 1.0 Universal (CC0 Public Domain Dedication)",
  url: "https://creativecommons.org/publicdomain/zero/1.0/"
)

#
# Contacts
#
Contact.create(
  slug: "rubenstein",
  name: "David M. Rubenstein Rare Book & Manuscript Library",
  short_name: "Rubenstein Library",
  url: "http://library.duke.edu/rubenstein/",
  phone: "919-660-5822",
  email: "special-collections@duke.edu",
  ask: "http://library.duke.edu/rubenstein/ask"
)
Contact.create(
  slug: "hartman",
  name: "John W. Hartman Center for Sales, Advertising & Marketing History",
  short_name: "Hartman Center",
  url: "http://library.duke.edu/rubenstein/hartman/",
  phone: "919-660-5827",
  email: "hartman-center@duke.edu",
  ask: "http://library.duke.edu/rubenstein/hartman/ask"
)
Contact.create(
  slug: "bingham",
  name: "Sallie Bingham Center for Women's History & Culture",
  short_name: "Bingham Center",
  url: "http://library.duke.edu/rubenstein/bingham/",
  phone: "919-660-5967",
  email: "cwhc@duke.edu",
  ask: "http://library.duke.edu/rubenstein/ask"
)
Contact.create(
  slug: "docarts",
  name: "Archive of Documentary Arts",
  url: "http://library.duke.edu/rubenstein/documentaryarts/",
  phone: "919-660-5822",
  email: "special-collections@duke.edu",
  ask: "http://library.duke.edu/rubenstein/ask"
)
Contact.create(
  slug: "franklin",
  name: "John Hope Franklin Research Center",
  short_name: "Franklin Research Center",
  url: "http://library.duke.edu/rubenstein/franklin/",
  phone: "919-660-5922",
  email: "franklin-collection@duke.edu",
  ask: "http://library.duke.edu/rubenstein/ask"
)
Contact.create(
  slug: "hom",
  name: "History of Medicine Collections",
  url: "http://library.duke.edu/rubenstein/history-of-medicine/",
  phone: "919-684-8549",
  email: "special-collections@duke.edu",
  ask: "http://library.duke.edu/rubenstein/ask"
)
Contact.create(
  slug: "humanrights",
  name: "Human Rights Archive",
  url: "http://library.duke.edu/rubenstein/human-rights/",
  phone: "919-660-5822",
  email: "special-collections@duke.edu",
  ask: "http://library.duke.edu/rubenstein/ask"
)
Contact.create(
  slug: "uarchives",
  name: "Duke University Archives",
  short_name: "University Archives",
  url: "http://library.duke.edu/rubenstein/uarchives/",
  phone: "919-660-5822",
  email: "uarchives@duke.edu",
  ask: "http://library.duke.edu/rubenstein/uarchives/ask"
)
Contact.create(
  slug: "divinity",
  name: "Divinity School Library",
  url: "http://library.divinity.duke.edu/",
  phone: "919-660-3453",
  email: "divlib@duke.edu",
  ask: "http://library.divinity.duke.edu/ask-us"
)
Contact.create(
  slug: "libraries",
  name: "Duke University Libraries",
  url: "http://library.duke.edu",
  phone: "919-660-5880",
  email: "askref@duke.edu",
  ask: "http://library.duke.edu/research/ask"
)

#
# Admin sets
#
AdminSet.create(
  code: "researchdata",
  title: "Duke Research Data"
)
AdminSet.create(
  code: "duke_scholarship",
  title: "Duke Scholarship"
)
AdminSet.create(
  code: "rubenstein",
  title: "Rubenstein Library"
)
AdminSet.create(
  code: "dvs",
  title: "Data and Visualization Services"
)
AdminSet.create(
  code: "dc",
  title: "Digital Collections"
)
AdminSet.create(
  code: "nescent",
  title: "NESCent: National Evolutionary Synthesis Center"
)

#
# Languages
#
languages = [
  ["asm", "Assamese"],
  ["bul", "Bulgarian"],
  ["ace", "Achinese"],
  ["ada", "Adangme"],
  ["akk", "Akkadian"],
  ["chk", "Chuukese"],
  ["aar", "Afar"],
  ["aka", "Akan"],
  ["afa", "Afro-Asiatic languages"],
  ["anp", "Angika"],
  ["ara", "Arabic"],
  ["hye", "Armenian"],
  ["arm", "Armenian"],
  ["ast", "Asturian; Bable; Leonese; Asturleonese"],
  ["eus", "Basque"],
  ["bik", "Bikol"],
  ["bal", "Baluchi"],
  ["bai", "Bamileke languages"],
  ["ang", "English, Old (ca.450-1100)"],
  ["alb", "Albanian"],
  ["apa", "Apache languages"],
  ["ale", "Aleut"],
  ["bih", "Bihari languages"],
  ["arc", "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)"],
  ["arp", "Arapaho"],
  ["bat", "Baltic languages"],
  ["afh", "Afrihili"],
  ["ach", "Acoli"],
  ["abk", "Abkhazian"],
  ["ady", "Adyghe; Adygei"],
  ["arn", "Mapudungun; Mapuche"],
  ["kin", "Kinyarwanda"],
  ["mni", "Manipuri"],
  ["din", "Dinka"],
  ["chn", "Chinook jargon"],
  ["aym", "Aymara"],
  ["dak", "Dakota"],
  ["ice", "Icelandic"],
  ["dgr", "Dogrib"],
  ["kam", "Kamba"],
  ["vot", "Votic"],
  ["mon", "Mongolian"],
  ["fre", "French"],
  ["pau", "Palauan"],
  ["isl", "Icelandic"],
  ["twi", "Twi"],
  ["rap", "Rapanui"],
  ["bin", "Bini; Edo"],
  ["nqo", "N'Ko"],
  ["rom", "Romany"],
  ["chy", "Cheyenne"],
  ["sah", "Yakut"],
  ["pli", "Pali"],
  ["slo", "Slovak"],
  ["roh", "Romansh"],
  ["uzb", "Uzbek"],
  ["cel", "Celtic languages"],
  ["hun", "Hungarian"],
  ["cop", "Coptic"],
  ["smj", "Lule Sami"],
  ["zho", "Chinese"],
  ["paa", "Papuan languages"],
  ["mas", "Masai"],
  ["ita", "Italian"],
  ["tuk", "Turkmen"],
  ["nso", "Pedi; Sepedi; Northern Sotho"],
  ["mah", "Marshallese"],
  ["cos", "Corsican"],
  ["car", "Galibi Carib"],
  ["tgl", "Tagalog"],
  ["vie", "Vietnamese"],
  ["kum", "Kumyk"],
  ["ton", "Tonga (Tonga Islands)"],
  ["uga", "Ugaritic"],
  ["luo", "Luo (Kenya and Tanzania)"],
  ["dzo", "Dzongkha"],
  ["yao", "Yao"],
  ["nub", "Nubian languages"],
  ["nah", "Nahuatl languages"],
  ["sme", "Northern Sami"],
  ["gem", "Germanic languages"],
  ["awa", "Awadhi"],
  ["vol", "Volapük"],
  ["ewe", "Ewe"],
  ["gba", "Gbaya"],
  ["phn", "Phoenician"],
  ["hmn", "Hmong; Mong"],
  ["kat", "Georgian"],
  ["est", "Estonian"],
  ["kaa", "Kara-Kalpak"],
  ["mos", "Mossi"],
  ["nya", "Chichewa; Chewa; Nyanja"],
  ["aze", "Azerbaijani"],
  ["ber", "Berber languages"],
  ["mar", "Marathi"],
  ["ava", "Avaric"],
  ["orm", "Oromo"],
  ["spa", "Spanish; Castilian"],
  ["fon", "Fon"],
  ["ron", "Romanian; Moldavian; Moldovan"],
  ["run", "Rundi"],
  ["kpe", "Kpelle"],
  ["btk", "Batak languages"],
  ["raj", "Rajasthani"],
  ["bis", "Bislama"],
  ["kal", "Kalaallisut; Greenlandic"],
  ["him", "Himachali languages; Western Pahari languages"],
  ["mic", "Mi'kmaq; Micmac"],
  ["tut", "Altaic languages"],
  ["ven", "Venda"],
  ["srp", "Serbian"],
  ["byn", "Blin; Bilin"],
  ["sel", "Selkup"],
  ["glg", "Galician"],
  ["bla", "Siksika"],
  ["ndo", "Ndonga"],
  ["chi", "Chinese"],
  ["bak", "Bashkir"],
  ["per", "Persian"],
  ["alt", "Southern Altai"],
  ["ain", "Ainu"],
  ["zul", "Zulu"],
  ["nau", "Nauru"],
  ["nog", "Nogai"],
  ["wak", "Wakashan languages"],
  ["sad", "Sandawe"],
  ["oci", "Occitan (post 1500)"],
  ["bad", "Banda languages"],
  ["zgh", "Standard Moroccan Tamazight"],
  ["mlt", "Maltese"],
  ["tvl", "Tuvalu"],
  ["cha", "Chamorro"],
  ["syc", "Classical Syriac"],
  ["sio", "Siouan languages"],
  ["mkd", "Macedonian"],
  ["chb", "Chibcha"],
  ["lol", "Mongo"],
  ["fur", "Friulian"],
  ["vai", "Vai"],
  ["gez", "Geez"],
  ["sit", "Sino-Tibetan languages"],
  ["sga", "Irish, Old (to 900)"],
  ["fra", "French"],
  ["khm", "Central Khmer"],
  ["egy", "Egyptian (Ancient)"],
  ["tai", "Tai languages"],
  ["hat", "Haitian; Haitian Creole"],
  ["nbl", "Ndebele, South; South Ndebele"],
  ["frs", "Eastern Frisian"],
  ["dan", "Danish"],
  ["cpf", "Creoles and pidgins, French-based"],
  ["msa", "Malay"],
  ["nde", "Ndebele, North; North Ndebele"],
  ["pol", "Polish"],
  ["nwc", "Classical Newari; Old Newari; Classical Nepal Bhasa"],
  ["afr", "Afrikaans"],
  ["mak", "Makasar"],
  ["ind", "Indonesian"],
  ["sus", "Susu"],
  ["hsb", "Upper Sorbian"],
  ["gon", "Gondi"],
  ["dsb", "Lower Sorbian"],
  ["zxx", "No linguistic content; Not applicable"],
  ["arw", "Arawak"],
  ["fij", "Fijian"],
  ["gwi", "Gwich'in"],
  ["srd", "Sardinian"],
  ["lin", "Lingala"],
  ["kbd", "Kabardian"],
  ["kab", "Kabyle"],
  ["snd", "Sindhi"],
  ["nld", "Dutch; Flemish"],
  ["goh", "German, Old High (ca.750-1050)"],
  ["ger", "German"],
  ["tat", "Tatar"],
  ["lun", "Lunda"],
  ["geo", "Georgian"],
  ["ile", "Interlingue; Occidental"],
  ["zun", "Zuni"],
  ["mac", "Macedonian"],
  ["jav", "Javanese"],
  ["was", "Washo"],
  ["sla", "Slavic languages"],
  ["rum", "Romanian; Moldavian; Moldovan"],
  ["tah", "Tahitian"],
  ["ban", "Balinese"],
  ["grn", "Guarani"],
  ["smi", "Sami languages"],
  ["cre", "Cree"],
  ["chr", "Cherokee"],
  ["smn", "Inari Sami"],
  ["krc", "Karachay-Balkar"],
  ["chv", "Chuvash"],
  ["sid", "Sidamo"],
  ["urd", "Urdu"],
  ["new", "Nepal Bhasa; Newari"],
  ["por", "Portuguese"],
  ["xho", "Xhosa"],
  ["lam", "Lamba"],
  ["bra", "Braj"],
  ["men", "Mende"],
  ["mus", "Creek"],
  ["sot", "Sotho, Southern"],
  ["kir", "Kirghiz; Kyrgyz"],
  ["sem", "Semitic languages"],
  ["hai", "Haida"],
  ["suk", "Sukuma"],
  ["bas", "Basa"],
  ["myn", "Mayan languages"],
  ["tyv", "Tuvinian"],
  ["tso", "Tsonga"],
  ["che", "Chechen"],
  ["mdr", "Mandar"],
  ["hil", "Hiligaynon"],
  ["nia", "Nias"],
  ["tkl", "Tokelau"],
  ["map", "Austronesian languages"],
  ["kut", "Kutenai"],
  ["got", "Gothic"],
  ["cus", "Cushitic languages"],
  ["epo", "Esperanto"],
  ["gil", "Gilbertese"],
  ["bnt", "Bantu languages"],
  ["nor", "Norwegian"],
  ["phi", "Philippine languages"],
  ["fil", "Filipino; Pilipino"],
  ["gaa", "Ga"],
  ["fiu", "Finno-Ugrian languages"],
  ["den", "Slave (Athapascan)"],
  ["ota", "Turkish, Ottoman (1500-1928)"],
  ["kau", "Kanuri"],
  ["ypk", "Yupik languages"],
  ["frr", "Northern Frisian"],
  ["mag", "Magahi"],
  ["ilo", "Iloko"],
  ["swa", "Swahili"],
  ["kik", "Kikuyu; Gikuyu"],
  ["lim", "Limburgan; Limburger; Limburgish"],
  ["eka", "Ekajuk"],
  ["mya", "Burmese"],
  ["mri", "Maori"],
  ["fin", "Finnish"],
  ["mkh", "Mon-Khmer languages"],
  ["krl", "Karelian"],
  ["slv", "Slovenian"],
  ["hit", "Hittite"],
  ["zza", "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki"],
  ["lat", "Latin"],
  ["mul", "Multiple languages"],
  ["lit", "Lithuanian"],
  ["lav", "Latvian"],
  ["inc", "Indic languages"],
  ["sna", "Shona"],
  ["ave", "Avestan"],
  ["umb", "Umbundu"],
  ["cpp", "Creoles and pidgins, Portuguese-based"],
  ["her", "Herero"],
  ["dut", "Dutch; Flemish"],
  ["lui", "Luiseno"],
  ["oss", "Ossetian; Ossetic"],
  ["sun", "Sundanese"],
  ["son", "Songhai languages"],
  ["iku", "Inuktitut"],
  ["dum", "Dutch, Middle (ca.1050-1350)"],
  ["rus", "Russian"],
  ["lua", "Luba-Lulua"],
  ["kac", "Kachin; Jingpho"],
  ["cpe", "Creoles and pidgins, English based"],
  ["sma", "Southern Sami"],
  ["efi", "Efik"],
  ["mai", "Maithili"],
  ["sin", "Sinhala; Sinhalese"],
  ["kor", "Korean"],
  ["hin", "Hindi"],
  ["nzi", "Nzima"],
  ["tig", "Tigre"],
  ["non", "Norse, Old"],
  ["ina", "Interlingua (International Auxiliary Language Association)"],
  ["kaz", "Kazakh"],
  ["jrb", "Judeo-Arabic"],
  ["bho", "Bhojpuri"],
  ["grb", "Grebo"],
  ["lus", "Lushai"],
  ["hup", "Hupa"],
  ["hrv", "Croatian"],
  ["ira", "Iranian languages"],
  ["tup", "Tupi languages"],
  ["bos", "Bosnian"],
  ["may", "Malay"],
  ["cmc", "Chamic languages"],
  ["jbo", "Lojban"],
  ["gay", "Gayo"],
  ["nic", "Niger-Kordofanian languages"],
  ["wen", "Sorbian languages"],
  ["heb", "Hebrew"],
  ["ibo", "Igbo"],
  ["cau", "Caucasian languages"],
  ["smo", "Samoan"],
  ["mao", "Maori"],
  ["cze", "Czech"],
  ["bur", "Burmese"],
  ["kan", "Kannada"],
  ["mno", "Manobo languages"],
  ["sag", "Sango"],
  ["scn", "Sicilian"],
  ["zap", "Zapotec"],
  ["nyn", "Nyankole"],
  ["bem", "Bemba"],
  ["mnc", "Manchu"],
  ["crh", "Crimean Tatar; Crimean Turkish"],
  ["div", "Divehi; Dhivehi; Maldivian"],
  ["ter", "Tereno"],
  ["kon", "Kongo"],
  ["pag", "Pangasinan"],
  ["ell", "Greek, Modern (1453-)"],
  ["gmh", "German, Middle High (ca.1050-1500)"],
  ["sms", "Skolt Sami"],
  ["nym", "Nyamwezi"],
  ["cat", "Catalan; Valencian"],
  ["dyu", "Dyula"],
  ["tam", "Tamil"],
  ["yor", "Yoruba"],
  ["tmh", "Tamashek"],
  ["fry", "Western Frisian"],
  ["khi", "Khoisan languages"],
  ["kro", "Kru languages"],
  ["uig", "Uighur; Uyghur"],
  ["baq", "Basque"],
  ["bod", "Tibetan"],
  ["cad", "Caddo"],
  ["nob", "Bokmål, Norwegian; Norwegian Bokmål"],
  ["wal", "Wolaitta; Wolaytta"],
  ["wel", "Welsh"],
  ["sco", "Scots"],
  ["man", "Mandingo"],
  ["tsi", "Tsimshian"],
  ["haw", "Hawaiian"],
  ["kar", "Karen languages"],
  ["fas", "Persian"],
  ["roa", "Romance languages"],
  ["chm", "Mari"],
  ["osa", "Osage"],
  ["mwl", "Mirandese"],
  ["sog", "Sogdian"],
  ["srn", "Sranan Tongo"],
  ["swe", "Swedish"],
  ["tha", "Thai"],
  ["tir", "Tigrinya"],
  ["udm", "Udmurt"],
  ["pus", "Pushto; Pashto"],
  ["shn", "Shan"],
  ["kas", "Kashmiri"],
  ["fat", "Fanti"],
  ["pal", "Pahlavi"],
  ["tel", "Telugu"],
  ["guj", "Gujarati"],
  ["lah", "Lahnda"],
  ["gre", "Greek, Modern (1453-)"],
  ["slk", "Slovak"],
  ["day", "Land Dayak languages"],
  ["tgk", "Tajik"],
  ["grc", "Greek, Ancient (to 1453)"],
  ["ben", "Bengali"],
  ["xal", "Kalmyk; Oirat"],
  ["bel", "Belarusian"],
  ["lub", "Luba-Katanga"],
  ["mis", "Uncoded languages"],
  ["jpn", "Japanese"],
  ["kaw", "Kawi"],
  ["oji", "Ojibwa"],
  ["bug", "Buginese"],
  ["del", "Delaware"],
  ["cho", "Choctaw"],
  ["niu", "Niuean"],
  ["ful", "Fulah"],
  ["lug", "Ganda"],
  ["san", "Sanskrit"],
  ["gsw", "Swiss German; Alemannic; Alsatian"],
  ["nyo", "Nyoro"],
  ["sal", "Salishan languages"],
  ["eng", "English"],
  ["ewo", "Ewondo"],
  ["hmo", "Hiri Motu"],
  ["moh", "Mohawk"],
  ["lez", "Lezghian"],
  ["dra", "Dravidian languages"],
  ["fan", "Fang"],
  ["cai", "Central American Indian languages"],
  ["kom", "Komi"],
  ["loz", "Lozi"],
  ["sux", "Sumerian"],
  ["sam", "Samaritan Aramaic"],
  ["csb", "Kashubian"],
  ["nno", "Norwegian Nynorsk; Nynorsk, Norwegian"],
  ["tet", "Tetum"],
  ["nav", "Navajo; Navaho"],
  ["sat", "Santali"],
  ["mdf", "Moksha"],
  ["bej", "Beja; Bedawiyet"],
  ["nai", "North American Indian languages"],
  ["wol", "Wolof"],
  ["sas", "Sasak"],
  ["som", "Somali"],
  ["gle", "Irish"],
  ["kru", "Kurukh"],
  ["que", "Quechua"],
  ["qaa-qtz", "Reserved for local use"],
  ["rup", "Aromanian; Arumanian; Macedo-Romanian"],
  ["pan", "Panjabi; Punjabi"],
  ["ine", "Indo-European languages"],
  ["wln", "Walloon"],
  ["pon", "Pohnpeian"],
  ["crp", "Creoles and pidgins"],
  ["mlg", "Malagasy"],
  ["mga", "Irish, Middle (900-1200)"],
  ["yid", "Yiddish"],
  ["ori", "Oriya"],
  ["iii", "Sichuan Yi; Nuosu"],
  ["aus", "Australian languages"],
  ["srr", "Serer"],
  ["iro", "Iroquoian languages"],
  ["zha", "Zhuang; Chuang"],
  ["chu", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"],
  ["tlh", "Klingon; tlhIngan-Hol"],
  ["deu", "German"],
  ["bua", "Buriat"],
  ["mun", "Munda languages"],
  ["gor", "Gorontalo"],
  ["hau", "Hausa"],
  ["bre", "Breton"],
  ["tsn", "Tswana"],
  ["ces", "Czech"],
  ["jpr", "Judeo-Persian"],
  ["peo", "Persian, Old (ca.600-400 B.C.)"],
  ["snk", "Soninke"],
  ["pra", "Prakrit languages"],
  ["ido", "Ido"],
  ["inh", "Ingush"],
  ["cor", "Cornish"],
  ["amh", "Amharic"],
  ["yap", "Yapese"],
  ["pam", "Pampanga; Kapampangan"],
  ["alg", "Algonquian languages"],
  ["ijo", "Ijo languages"],
  ["kur", "Kurdish"],
  ["tur", "Turkish"],
  ["lad", "Ladino"],
  ["chp", "Chipewyan; Dene Suline"],
  ["kho", "Khotanese; Sakan"],
  ["myv", "Erzya"],
  ["fao", "Faroese"],
  ["chg", "Chagatai"],
  ["ssw", "Swati"],
  ["fro", "French, Old (842-ca.1400)"],
  ["tpi", "Tok Pisin"],
  ["kua", "Kuanyama; Kwanyama"],
  ["art", "Artificial languages"],
  ["kok", "Konkani"],
  ["war", "Waray"],
  ["pap", "Papiamento"],
  ["cym", "Welsh"],
  ["und", "Undetermined"],
  ["ipk", "Inupiaq"],
  ["sgn", "Sign Languages"],
  ["iba", "Iban"],
  ["ath", "Athapascan languages"],
  ["tog", "Tonga (Nyasa)"],
  ["kha", "Khasi"],
  ["arg", "Aragonese"],
  ["glv", "Manx"],
  ["rar", "Rarotongan; Cook Islands Maori"],
  ["dar", "Dargwa"],
  ["tib", "Tibetan"],
  ["doi", "Dogri"],
  ["syr", "Syriac"],
  ["dua", "Duala"],
  ["tem", "Timne"],
  ["znd", "Zande languages"],
  ["tiv", "Tiv"],
  ["ceb", "Cebuano"],
  ["enm", "English, Middle (1100-1500)"],
  ["min", "Minangkabau"],
  ["nap", "Neapolitan"],
  ["gla", "Gaelic; Scottish Gaelic"],
  ["kos", "Kosraean"],
  ["sqi", "Albanian"],
  ["mwr", "Marwari"],
  ["zbl", "Blissymbols; Blissymbolics; Bliss"],
  ["nds", "Low German; Low Saxon; German, Low; Saxon, Low"],
  ["kmb", "Kimbundu"],
  ["frm", "French, Middle (ca.1400-1600)"],
  ["zen", "Zenaga"],
  ["mad", "Madurese"],
  ["pro", "Provençal, Old (to 1500); Occitan, Old (to 1500)"],
  ["ssa", "Nilo-Saharan languages"],
  ["sai", "South American Indian languages"],
  ["nep", "Nepali"],
  ["elx", "Elamite"],
  ["mal", "Malayalam"],
  ["lao", "Lao"],
  ["tum", "Tumbuka"],
  ["oto", "Otomian languages"],
  ["bam", "Bambara"],
  ["ukr", "Ukrainian"],
  ["ltz", "Luxembourgish; Letzeburgesch"],
  ["tli", "Tlingit"]
]

languages.each do |code, label|
  Language.create(code: code, label: label)
end
